spring:
  datasource:
    url: jdbc:sqlite:./neocourse.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

neocourse:
  administrator:
    username: ${NEOCOURSE_ADMINISTRATOR_USERNAME:}
    displayed-username: ${NEOCOURSE_ADMINISTRATOR_DISPLAYED_USERNAME:}
    password: ${NEOCOURSE_ADMINISTRATOR_PASSWORD:}